stages:
  - build
  - test
  - snyk-scan
  - upload-s3
  
variables:
  MAVEN_CLI_OPTS: "-s setting.xml"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install -Dproperty=value -DskipTests

  tags:
    - shared

  artifacts:
    when: always
    expire_in: 30days
    paths:
      - mkdir builds/EmployeeApp
      - builds/EmployeeApp
