stages:
  - build
  - test
  - snyk-scan
  - upload-s3

variables:
  MAVEN_CLI_OPTS: "-s setting.xml"

# include:
#   - local: fetch_db_pass.sh  # Include the script to fetch DB_PASS

# .pre-setup:
#   script:
#     - sudo apt-get update && sudo apt-get install jq
#     - chmod +x fetch_db_pass.sh
#     - ./fetch_db_pass.sh  # Execute the script to obtain and export DB_PASS
#     - echo "DB_PASS in .pre-setup: $DB_PASS" 
#     # You can use the exported DB_PASS in this job

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:latest
  script:
    - apt-get update 
    - apt-get install -y jq 
    - echo "installed jq"
    - chmod +x fetch_db_pass.sh
    - ./fetch_db_pass.sh  # Execute the script to obtain and export DB_PASS
    # - echo "DB_PASS in .pre-setup: $DB_PASS" 
    - if [ -z "$DB_PASS" ]; then echo "DB_PASS not available"; exit 1; fi
    - mvn clean install -Dproperty=value 
  tags:
    - shared
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - builds/EmployeeApp
