stages:
  - build
  - test
  - snyk-scan
  - upload-s3

variables:
  MAVEN_CLI_OPTS: "-s setting.xml"

.pre-setup:
  script:
    - apt-get update
    - apt-get install -y jq
    - chmod +x fetch_db_pass.sh
    - ./fetch_db_pass.sh  # Execute the script to obtain and export DB_PASSWORD
    - echo "DB_PASSWORD in .pre-setup: $DB_PASSWORD"  # Debugging statement

cache:
  paths:
    - .m2/repository

build:
  stage: build
  extends:
    .pre-setup
  image: maven:latest
  script:
    - if [ -z "$DB_PASSWORD" ]; then echo "DB_PASSWORD not available"; exit 1; fi
    - echo "Using DB_PASSWORD: $DB_PASSWORD"
    - mvn clean install -Dproperty=value
  tags:
    - shared
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - builds/EmployeeApp
