stages:
  - build
  - test
  - snyk-scan
  - upload-s3
  
variables:
  MAVEN_CLI_OPTS: "-s setting.xml"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn {MAVEN_CLI_OPTS} clean install

  rules:
    - if: ($BuildType == "CI" || $BuildType == "ci")

  tags:
    - shared

  artifacts:
    when: always
    expire_in: 30days
    paths:
      - mkdir builds/EmployeeApp
      - builds/EmployeeApp
